; PlatformIO Project Configuration File
; ESP8266 NodeMCU build for Shabbat Alert

[platformio]
default_envs = esp8266mod
src_dir = src
data_dir = data

[env:esp8266mod]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 230400
platform_packages =
    platformio/tool-esptoolpy@~2.40900.0
build_flags =
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_ESP8266=1
    -DUSE_OLED=0
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    earlephilhower/ESP8266Audio
    adafruit/Adafruit NeoPixel@^1.12.0
