#include "storage.h"
#include "hebcal_client.h"   // for ShabbatEvent struct
#include <cmath>

namespace {
bool s_configCacheValid = false;
bool s_configuredCached = false;

// Deferred-commit batching.  When s_deferCommit is true, writeXxx() helpers
// update the EEPROM RAM buffer but skip the flash erase; endBatch() does one
// commit at the end.  Cuts a 15-field settings save from ~450ms to ~30ms.
bool s_deferCommit = false;
bool s_deferDirty = false;

// In-memory cache of all settings.  Populated lazily from EEPROM/Preferences
// and updated synchronously on every setter, so getters never re-read flash
// (avoids dozens of small heap allocations per second under heavy polling).
struct StorageCache {
    bool loaded;
    String wifiSSID;
    String wifiPassword;
    String cityName;
    String timezone;
    String ringtone;
    String havdalahMode;
    String hebcalProxyURL;
    String settingsPassword;
    String lastSchedule;
    float latitude;
    float longitude;
    float havdalahDegrees;
    int candleOffset;
    int havdalahMinutes;
    int candleAlerts;
    int hebcalMaxAttempts;
    int beepDurationMs;
    int beepPauseMs;
    int alertBeepCount;
    int geonameID;
    bool alertEnabled;
    unsigned long alertDurationMs;
    unsigned long lastScheduleTime;
};
StorageCache s_cache = {};
}

static void storageInvalidateConfigCache() {
    s_configCacheValid = false;
}

bool Storage::eepromInitialized = false;

// EEPROM address offsets (expanded for persisted schedule cache)
#define EEPROM_SIZE 1024
#define ADDR_WIFI_SSID 0
#define ADDR_WIFI_PASS 64
#define ADDR_CITY_NAME 128
#define ADDR_TIMEZONE 192
#define ADDR_SETTINGS_PASS 256
#define ADDR_LAST_SCHEDULE 320
#define ADDR_LATITUDE 384
#define ADDR_LONGITUDE 388
#define ADDR_GEONAMEID 392
#define ADDR_CANDLE_OFFSET 396
#define ADDR_HAVDALAH_MODE 400
#define ADDR_HAVDALAH_MINUTES 404
#define ADDR_ALERT_ENABLED 408
#define ADDR_LAST_SCHEDULE_TIME 412
#define ADDR_BEEP_DURATION_MS 416
#define ADDR_BEEP_PAUSE_MS 420
#define ADDR_ALERT_BEEP_COUNT 424
#define ADDR_ALERT_DURATION_MS 428
#define ADDR_HAVDALAH_DEGREES 432
#define ADDR_RINGTONE 436
#define RINGTONE_MAX_LEN 24
#define ADDR_HEBCAL_MAX_ATTEMPTS 500
#define ADDR_HEBCAL_PROXY_URL 504
#define HEBCAL_PROXY_URL_MAX_LEN 96
#define ADDR_CANDLE_ALERTS 600
// Persisted Hebcal runtime cache (multi-event layout).
//
//   604      magic byte (= SCH_CACHE_MAGIC)
//   605      event count (0..SCH_MAX_PERSIST)
//   606..    SCH_MAX_PERSIST entries × 17 bytes each
//              per entry: 4 bytes UTC ts + 1 byte kind + 12 bytes title (NUL-padded)
//
// Display strings ("YYYY-MM-DD HH:MM" for next candle / next havdalah) are
// NOT persisted — they're regenerated by the scheduler from the restored
// events on every boot.  Saves ~60 bytes of EEPROM and keeps us safely below
// the Diag ring buffer at addr 720.
#define ADDR_SCH_MAGIC          604
#define ADDR_SCH_COUNT          605
#define ADDR_SCH_EVENTS_BASE    606
#define SCH_EVENT_SIZE          17
#define SCH_MAX_PERSIST         6
// 606 + 6*17 = 708.  Diag at 720 → 12-byte safety gap.

void Storage::loadCache() {
    if (s_cache.loaded) return;
    s_cache.wifiSSID = Storage::readString(ADDR_WIFI_SSID, 64);
    s_cache.wifiPassword = Storage::readString(ADDR_WIFI_PASS, 64);
    s_cache.cityName = Storage::readString(ADDR_CITY_NAME, 64);
    s_cache.latitude = Storage::readFloat(ADDR_LATITUDE);
    s_cache.longitude = Storage::readFloat(ADDR_LONGITUDE);
    {
        String tz = Storage::readString(ADDR_TIMEZONE, 64);
        s_cache.timezone = tz.length() > 0 ? tz : String(DEFAULT_TIMEZONE);
    }
    s_cache.geonameID = Storage::readInt(ADDR_GEONAMEID);
    {
        // Uninitialised EEPROM (0xFFFFFFFF) reads as -1 here; the old `v != 0`
        // check accepted that, sending b=-1 to Hebcal and pushing candle
        // lighting to sunset itself.  Reject anything outside the plausible
        // 0–60 minute range.
        int v = Storage::readInt(ADDR_CANDLE_OFFSET);
        s_cache.candleOffset = (v >= 0 && v <= 60) ? v : DEFAULT_CANDLE_OFFSET;
    }
    {
        String mode = Storage::readString(ADDR_HAVDALAH_MODE, 2);
        s_cache.havdalahMode = mode.length() > 0 ? mode : String(DEFAULT_HAVDALAH_MODE);
    }
    {
        int v = Storage::readInt(ADDR_HAVDALAH_MINUTES);
        // Same EEPROM-uninit guard as candle_offset; -1 here would silently
        // send m=-1 to Hebcal when havdalah_mode is "m".
        s_cache.havdalahMinutes = (v > 0 && v <= 180) ? v : DEFAULT_HAVDALAH_MINUTES;
    }
    {
        float v = Storage::readFloat(ADDR_HAVDALAH_DEGREES);
        s_cache.havdalahDegrees = (v > 0.0f) ? v : DEFAULT_HAVDALAH_DEGREES;
    }
    s_cache.alertEnabled = Storage::readBool(ADDR_ALERT_ENABLED);
    {
        int v = Storage::readInt(ADDR_BEEP_DURATION_MS);
        s_cache.beepDurationMs = (v > 0) ? v : DEFAULT_BEEP_DURATION_MS;
    }
    {
        int v = Storage::readInt(ADDR_BEEP_PAUSE_MS);
        s_cache.beepPauseMs = (v > 0) ? v : DEFAULT_BEEP_PAUSE_MS;
    }
    {
        int v = Storage::readInt(ADDR_ALERT_BEEP_COUNT);
        s_cache.alertBeepCount = (v > 0) ? v : ALERT_BEEP_COUNT;
    }
    {
        // CRITICAL: uninitialised EEPROM (0xFFFFFFFF) reads as UINT32_MAX
        // here.  The old `v > 0` check accepted it, so activeDurationMs
        // became ~49 days — updateLED's `elapsed < activeDurationMs` stayed
        // true forever, isActive never cleared, and every subsequent alert
        // for the rest of the boot session was silently dropped.  Cap at
        // 60 s (way longer than any reasonable ringtone) so a bogus EEPROM
        // value can't permanently jam the alert subsystem.
        unsigned long v = Storage::readULong(ADDR_ALERT_DURATION_MS);
        s_cache.alertDurationMs = (v > 0 && v <= 60000UL) ? v : ALERT_DURATION_MS;
    }
    {
        String v = Storage::readString(ADDR_RINGTONE, RINGTONE_MAX_LEN);
        s_cache.ringtone = v.length() > 0 ? v : String(DEFAULT_RINGTONE);
    }
    s_cache.settingsPassword = Storage::readString(ADDR_SETTINGS_PASS, 64);
    s_cache.lastSchedule = Storage::readString(ADDR_LAST_SCHEDULE, 64);
    s_cache.lastScheduleTime = Storage::readULong(ADDR_LAST_SCHEDULE_TIME);
    {
        int v = Storage::readInt(ADDR_HEBCAL_MAX_ATTEMPTS);
        s_cache.hebcalMaxAttempts = (v < 1 || v > 5) ? DEFAULT_HEBCAL_MAX_ATTEMPTS : v;
    }
    s_cache.hebcalProxyURL = Storage::readString(ADDR_HEBCAL_PROXY_URL, HEBCAL_PROXY_URL_MAX_LEN);
    {
        int v = Storage::readInt(ADDR_CANDLE_ALERTS);
        s_cache.candleAlerts = (v > 0 && v <= 7) ? v : DEFAULT_CANDLE_ALERTS;
    }
    s_cache.loaded = true;
}

bool Storage::init() {
    if (!eepromInitialized) {
        EEPROM.begin(EEPROM_SIZE);
        eepromInitialized = true;
    }
    storageInvalidateConfigCache();
    s_cache.loaded = false;
    loadCache();
    return true;
}

void Storage::clear() {
    for (int i = 0; i < EEPROM_SIZE; i++) {
        EEPROM.write(i, 0);
    }
    EEPROM.commit();
    storageInvalidateConfigCache();
    s_cache.loaded = false;
    loadCache();
}

String Storage::readString(int address, int maxLen) {
    String result = "";
    for (int i = 0; i < maxLen; i++) {
        char c = EEPROM.read(address + i);
        if (c == 0 || c == 255) break;
        result += c;
    }
    return result;
}

void Storage::writeString(int address, const String& value) {
    int len = value.length();
    if (len > 63) len = 63; // Max 63 chars + null terminator
    for (int i = 0; i < len; i++) {
        EEPROM.write(address + i, value[i]);
    }
    EEPROM.write(address + len, 0); // Null terminator
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

float Storage::readFloat(int address) {
    union {
        float f;
        byte b[4];
    } data;
    for (int i = 0; i < 4; i++) {
        data.b[i] = EEPROM.read(address + i);
    }
    return data.f;
}

void Storage::writeFloat(int address, float value) {
    union {
        float f;
        byte b[4];
    } data;
    data.f = value;
    for (int i = 0; i < 4; i++) {
        EEPROM.write(address + i, data.b[i]);
    }
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

int Storage::readInt(int address) {
    return (int)EEPROM.read(address) | ((int)EEPROM.read(address + 1) << 8) |
           ((int)EEPROM.read(address + 2) << 16) | ((int)EEPROM.read(address + 3) << 24);
}

void Storage::writeInt(int address, int value) {
    EEPROM.write(address, value & 0xFF);
    EEPROM.write(address + 1, (value >> 8) & 0xFF);
    EEPROM.write(address + 2, (value >> 16) & 0xFF);
    EEPROM.write(address + 3, (value >> 24) & 0xFF);
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

unsigned long Storage::readULong(int address) {
    unsigned long result = 0;
    for (int i = 0; i < 4; i++) {
        result |= ((unsigned long)EEPROM.read(address + i)) << (i * 8);
    }
    return result;
}

void Storage::writeULong(int address, unsigned long value) {
    for (int i = 0; i < 4; i++) {
        EEPROM.write(address + i, (value >> (i * 8)) & 0xFF);
    }
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

bool Storage::readBool(int address) {
    return EEPROM.read(address) != 0;
}

void Storage::writeBool(int address, bool value) {
    EEPROM.write(address, value ? 1 : 0);
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

void Storage::beginBatch() {
    s_deferCommit = true;
    s_deferDirty = false;
}

void Storage::endBatch() {
    s_deferCommit = false;
    if (s_deferDirty) {
        EEPROM.commit();
        s_deferDirty = false;
    }
}

// Implementation for ESP8266 (init and clear are already defined above).
// All getters return from the in-memory cache; setters keep the cache in sync.

String Storage::getWiFiSSID() { loadCache(); return s_cache.wifiSSID; }

void Storage::setWiFiSSID(const String& ssid) {
    writeString(ADDR_WIFI_SSID, ssid);
    s_cache.wifiSSID = ssid;
    storageInvalidateConfigCache();
}

String Storage::getWiFiPassword() { loadCache(); return s_cache.wifiPassword; }

void Storage::setWiFiPassword(const String& password) {
    writeString(ADDR_WIFI_PASS, password);
    s_cache.wifiPassword = password;
}

String Storage::getCityName() { loadCache(); return s_cache.cityName; }

void Storage::setCityName(const String& city) {
    writeString(ADDR_CITY_NAME, city);
    s_cache.cityName = city;
}

float Storage::getLatitude() { loadCache(); return s_cache.latitude; }

void Storage::setLatitude(float lat) {
    writeFloat(ADDR_LATITUDE, lat);
    s_cache.latitude = lat;
    storageInvalidateConfigCache();
    invalidateScheduleRuntimeCache();
}

float Storage::getLongitude() { loadCache(); return s_cache.longitude; }

void Storage::setLongitude(float lon) {
    writeFloat(ADDR_LONGITUDE, lon);
    s_cache.longitude = lon;
    storageInvalidateConfigCache();
    invalidateScheduleRuntimeCache();
}

String Storage::getTimezone() { loadCache(); return s_cache.timezone; }

void Storage::setTimezone(const String& tz) {
    writeString(ADDR_TIMEZONE, tz);
    s_cache.timezone = tz.length() > 0 ? tz : String(DEFAULT_TIMEZONE);
}

int Storage::getGeonameID() { loadCache(); return s_cache.geonameID; }

void Storage::setGeonameID(int id) {
    writeInt(ADDR_GEONAMEID, id);
    s_cache.geonameID = id;
}

int Storage::getCandleOffset() { loadCache(); return s_cache.candleOffset; }

void Storage::setCandleOffset(int minutes) {
    int sane = (minutes >= 0 && minutes <= 60) ? minutes : DEFAULT_CANDLE_OFFSET;
    writeInt(ADDR_CANDLE_OFFSET, sane);
    s_cache.candleOffset = sane;
}

String Storage::getHavdalahMode() {
    loadCache();
    // EEPROM slot for havdalah_mode is only 4 bytes wide (next slot is at +4),
    // so we persist a short canonical token: "M", "m", or "d".  Translate "d"
    // back to "degrees" for the rest of the firmware which compares against the
    // long string in URL building and JSON serialization.  Legacy devices that
    // had "degrees" written before this fix have a truncated "de" in EEPROM —
    // treat that the same as "d".
    if (s_cache.havdalahMode == "d" || s_cache.havdalahMode == "de") {
        return String("degrees");
    }
    return s_cache.havdalahMode;
}

void Storage::setHavdalahMode(const String& mode) {
    // Map the long external form to a 1-char token so it fits in 4 bytes
    // (writing "degrees" here used to silently clobber havdalah_minutes at
    // ADDR_HAVDALAH_MODE+4).
    String canonical = mode;
    if (mode == "degrees") canonical = "d";
    else if (mode.length() > 2) canonical = mode.substring(0, 1);  // belt+braces
    writeString(ADDR_HAVDALAH_MODE, canonical);
    s_cache.havdalahMode = canonical.length() > 0 ? canonical : String(DEFAULT_HAVDALAH_MODE);
}

int Storage::getHavdalahMinutes() { loadCache(); return s_cache.havdalahMinutes; }

void Storage::setHavdalahMinutes(int minutes) {
    int sane = (minutes > 0 && minutes <= 180) ? minutes : DEFAULT_HAVDALAH_MINUTES;
    writeInt(ADDR_HAVDALAH_MINUTES, sane);
    s_cache.havdalahMinutes = sane;
}

float Storage::getHavdalahDegrees() { loadCache(); return s_cache.havdalahDegrees; }

void Storage::setHavdalahDegrees(float degrees) {
    writeFloat(ADDR_HAVDALAH_DEGREES, degrees);
    s_cache.havdalahDegrees = degrees;
}

bool Storage::getAlertEnabled() { loadCache(); return s_cache.alertEnabled; }

void Storage::setAlertEnabled(bool enabled) {
    writeBool(ADDR_ALERT_ENABLED, enabled);
    s_cache.alertEnabled = enabled;
}

int Storage::getBeepDurationMs() { loadCache(); return s_cache.beepDurationMs; }

void Storage::setBeepDurationMs(int ms) {
    writeInt(ADDR_BEEP_DURATION_MS, ms);
    s_cache.beepDurationMs = (ms > 0) ? ms : DEFAULT_BEEP_DURATION_MS;
}

int Storage::getBeepPauseMs() { loadCache(); return s_cache.beepPauseMs; }

void Storage::setBeepPauseMs(int ms) {
    writeInt(ADDR_BEEP_PAUSE_MS, ms);
    s_cache.beepPauseMs = (ms > 0) ? ms : DEFAULT_BEEP_PAUSE_MS;
}

int Storage::getAlertBeepCount() { loadCache(); return s_cache.alertBeepCount; }

void Storage::setAlertBeepCount(int count) {
    writeInt(ADDR_ALERT_BEEP_COUNT, count);
    s_cache.alertBeepCount = (count > 0) ? count : ALERT_BEEP_COUNT;
}

unsigned long Storage::getAlertDurationMs() { loadCache(); return s_cache.alertDurationMs; }

void Storage::setAlertDurationMs(unsigned long ms) {
    unsigned long sane = (ms > 0 && ms <= 60000UL) ? ms : (unsigned long)ALERT_DURATION_MS;
    writeULong(ADDR_ALERT_DURATION_MS, sane);
    s_cache.alertDurationMs = sane;
}

String Storage::getRingtone() { loadCache(); return s_cache.ringtone; }

void Storage::setRingtone(const String& value) {
    writeString(ADDR_RINGTONE, value);
    s_cache.ringtone = value.length() > 0 ? value : String(DEFAULT_RINGTONE);
}

String Storage::getSettingsPassword() { loadCache(); return s_cache.settingsPassword; }

void Storage::setSettingsPassword(const String& password) {
    writeString(ADDR_SETTINGS_PASS, password);
    s_cache.settingsPassword = password;
}

String Storage::getLastSchedule() { loadCache(); return s_cache.lastSchedule; }

void Storage::setLastSchedule(const String& schedule) {
    writeString(ADDR_LAST_SCHEDULE, schedule);
    s_cache.lastSchedule = schedule;
}

unsigned long Storage::getLastScheduleTime() { loadCache(); return s_cache.lastScheduleTime; }

void Storage::setLastScheduleTime(unsigned long time) {
    writeULong(ADDR_LAST_SCHEDULE_TIME, time);
    s_cache.lastScheduleTime = time;
}

int Storage::getHebcalMaxAttempts() { loadCache(); return s_cache.hebcalMaxAttempts; }

void Storage::setHebcalMaxAttempts(int attempts) {
    if (attempts < 1) attempts = 1;
    if (attempts > 5) attempts = 5;
    writeInt(ADDR_HEBCAL_MAX_ATTEMPTS, attempts);
    s_cache.hebcalMaxAttempts = attempts;
}

String Storage::getHebcalProxyURL() { loadCache(); return s_cache.hebcalProxyURL; }

void Storage::setHebcalProxyURL(const String& url) {
    writeString(ADDR_HEBCAL_PROXY_URL, url);
    s_cache.hebcalProxyURL = url;
}

int Storage::getCandleAlerts() { loadCache(); return s_cache.candleAlerts; }

void Storage::setCandleAlerts(int bitmask) {
    writeInt(ADDR_CANDLE_ALERTS, bitmask);
    s_cache.candleAlerts = (bitmask > 0 && bitmask <= 7) ? bitmask : DEFAULT_CANDLE_ALERTS;
}

void Storage::persistScheduleRuntimeCache(const ShabbatEvent* events, int count,
                                          const String& /*nextCandles*/, const String& /*nextHavdalah*/) {
    if (count < 0) count = 0;
    if (count > SCH_MAX_PERSIST) count = SCH_MAX_PERSIST;
    EEPROM.write(ADDR_SCH_MAGIC, SCH_CACHE_MAGIC);
    EEPROM.write(ADDR_SCH_COUNT, (uint8_t)count);
    for (int i = 0; i < count; i++) {
        int addr = ADDR_SCH_EVENTS_BASE + i * SCH_EVENT_SIZE;
        uint32_t ts = (uint32_t)events[i].timestamp;
        EEPROM.write(addr + 0,  ts & 0xFF);
        EEPROM.write(addr + 1, (ts >> 8) & 0xFF);
        EEPROM.write(addr + 2, (ts >> 16) & 0xFF);
        EEPROM.write(addr + 3, (ts >> 24) & 0xFF);
        EEPROM.write(addr + 4, (uint8_t)events[i].kind);
        // Title: up to 12 bytes, NUL-padded.
        for (int t = 0; t < 12; t++) {
            EEPROM.write(addr + 5 + t, (uint8_t)events[i].title[t]);
        }
    }
    EEPROM.commit();
}

int Storage::loadScheduleRuntimeCache(ShabbatEvent* out, int maxOut,
                                      String& nextCandles, String& nextHavdalah) {
    nextCandles = "";
    nextHavdalah = "";
    if ((uint8_t)EEPROM.read(ADDR_SCH_MAGIC) != (uint8_t)SCH_CACHE_MAGIC) return 0;
    int count = (int)(uint8_t)EEPROM.read(ADDR_SCH_COUNT);
    if (count <= 0 || count > SCH_MAX_PERSIST) return 0;
    if (count > maxOut) count = maxOut;
    for (int i = 0; i < count; i++) {
        int addr = ADDR_SCH_EVENTS_BASE + i * SCH_EVENT_SIZE;
        uint32_t ts = 0;
        ts |= ((uint32_t)EEPROM.read(addr + 0));
        ts |= ((uint32_t)EEPROM.read(addr + 1)) << 8;
        ts |= ((uint32_t)EEPROM.read(addr + 2)) << 16;
        ts |= ((uint32_t)EEPROM.read(addr + 3)) << 24;
        out[i].timestamp = (time_t)ts;
        out[i].kind = (ShabbatKind)EEPROM.read(addr + 4);
        for (int t = 0; t < 12; t++) {
            out[i].title[t] = (char)EEPROM.read(addr + 5 + t);
        }
        // Defensive NUL — slot is 16 bytes but we only persist 12, so ensure
        // the rest is zeroed in case caller iterates past byte 11.
        for (int t = 12; t < 16; t++) out[i].title[t] = 0;
    }
    return count;
}

void Storage::invalidateScheduleRuntimeCache() {
    EEPROM.write(ADDR_SCH_MAGIC, 0);
    // Honour the active batch so that setLatitude/setLongitude inside a
    // settings POST don't trigger an early flash erase that defeats the batch.
    if (s_deferCommit) s_deferDirty = true;
    else EEPROM.commit();
}

bool Storage::isConfigured() {
    if (!s_configCacheValid) {
        float lat = getLatitude();
        float lon = getLongitude();
        // NaN != 0.0 evaluates true in IEEE 754, so the old check used to
        // report a freshly-initialised device (0xFF EEPROM bytes → NaN floats)
        // as "configured" and let refreshSchedule fire with bogus coords.
        bool latValid = std::isfinite(lat) && lat != 0.0f;
        bool lonValid = std::isfinite(lon) && lon != 0.0f;
        s_configuredCached = getWiFiSSID().length() > 0 && latValid && lonValid;
        s_configCacheValid = true;
    }
    return s_configuredCached;
}
